data_fraction: 0.1
num_angle_parts: 64
# geometric_index: -1 # angle part index, if -1 compute for all

seed: 1000 #TODO: consider different seeds

max_p: 20
q: -1
optimiser: "COBYLA"

num_anneal_fractions: 11

maxcut_max_qubits: 10

geometric_index: -1 # angle part index, if -1 compute for all